blank_issues_enabled: true
contact_links:
  - name: General Discussion and Questions
    url: "https://github.com/roger-protocol/roger-specs/discussions"
    about: Please ask questions or start a discussion here instead of openning an issue
